### PR TITLE
Pr/4

### PR DESCRIPTION
**Pull request by TylerBarnes**
@justinwhall there were a couple issues, had a look and fixed it up tho :)

### CODE REVIEW

**Comment by TylerBarnes** [comment]
huh, I'm not sure how to add you as a reviewer :p I can't even github

**Review by jasonbahl — APPROVED** [review]

**Comment by justinwhall** [comment]
🚀

**Comment by TylerBarnes** [comment]
Thanks @justinwhall !

**Comment by TylerBarnes** [comment]
And @jasonbahl too!

**Comment by TylerBarnes** [comment]
You guys ever notice your names rhyme really well? @jasonbahl @justinwhall

**Pull request merged**
